version: "3.8"
services:
    main:
        hostname: jenkins-main
        build:
            context: .
            dockerfile: Dockerfile.main
        ports:
            - "80:8080"
        networks:
            - jenkins
        volumes:
            - ./jenkins_data:/var/run/docker.sock    
    
    worker1:
        hostname: worker1
        build:
            context: .
            dockerfile: Dockerfile.worker

        networks:
            - jenkins
        environment:
            SSH_USERNAME: jenkins
            SSH_USERPASS: jenkins
        volumes:
            - ./jenkins_data:/var/run/docker.sock    

    worker2:
        hostname: worker2
        build:
            context: .
            dockerfile: Dockerfile.worker

        networks:
            - jenkins
        environment:
            SSH_USERNAME: jenkins
            SSH_USERPASS: jenkins
        volumes:
            - ./jenkins_data:/var/run/docker.sock    

networks:
    jenkins:
